CREATE DATABASE IF NOT EXISTS LABORATORIO;
SHOW DATABASES;

USE LABORATORIO;


CREATE TABLE IF NOT EXISTS FACTURAS(
Letra CHAR,
Numero INT UNSIGNED,
PRIMARY KEY(Letra,Numero),
ClienteID INT UNSIGNED NOT NULL,
ArticuloID INT UNSIGNED NOT NULL,
Fecha DATETIME,
Monto DOUBLE UNSIGNED
);

CREATE TABLE IF NOT EXISTS ARTICULOS(
ArticuloID INT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Precio DOUBLE UNSIGNED NOT NULL,
Stock INT NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTES(
ClienteID INT PRIMARY KEY,
Nombre VARCHAR(25) NOT NULL,
Apellido VARCHAR(25) NOT NULL,
CUIT CHAR(16) NOT NULL,
Direccion VARCHAR(50) NOT NULL,
Comentarios VARCHAR(50)
);

SHOW DATABASES;
SHOW TABLES;
DESCRIBE CLIENTES;
-- Hasta aca es el punto 1.1
-- Inicia el punto 1.2

ALTER TABLE FACTURAS CHANGE COLUMN ClienteID IDCliente INT UNSIGNED NOT NULL, CHANGE COLUMN ArticuloID IDArticulo INT UNSIGNED NOT NULL, MODIFY Monto DOUBLE UNSIGNED;

ALTER TABLE ARTICULOS DROP PRIMARY KEY, CHANGE COLUMN ArticuloID IDArticulo INT PRIMARY KEY, MODIFY Nombre VARCHAR(75) NOT NULL, MODIFY Precio DOUBLE UNSIGNED NOT NULL, MODIFY Stock INT UNSIGNED NOT NULL;

ALTER TABLE CLIENTES DROP PRIMARY KEY, CHANGE COLUMN ClienteID IDCliente INT PRIMARY KEY, MODIFY Nombre VARCHAR(30) NOT NULL, MODIFY Apellido VARCHAR(35) NOT NULL, CHANGE COLUMN Comentarios Observaciones VARCHAR(50), MODIFY Observaciones VARCHAR (255);

-- Hasta aca punto 1.2
-- Inicia el punto 1.3

INSERT INTO FACTURAS VALUES('A',28,14,335,2021-03-18,1589.50);
INSERT INTO FACTURAS VALUES('A',39,26,157,2021-04-12,979.75);
INSERT INTO FACTURAS VALUES('B',8,17,95,2021-04-25,513.35);
INSERT INTO FACTURAS VALUES('B',12,5,411,2021-05-03,2385.70);
INSERT INTO FACTURAS VALUES('B',19,50,157,2021-05-26,979.75);

INSERT INTO ARTICULOS VALUES(95,"Webcam con Micrófono Plug & Play",513.35,39);
INSERT INTO ARTICULOS VALUES(157,"Apple AirPods Pro",979.75,152);
INSERT INTO ARTICULOS VALUES(335,"Lavasecarropas Automático Samsung",1589.50,12);
INSERT INTO ARTICULOS VALUES(411,"Gloria Trevi / Gloria / CD+DVD",2385.70,2);

INSERT INTO CLIENTES VALUES(5,"Santiago","Gonzales",'23-24582359-9',"Uriburu 558 - 7ºA","VIP");
INSERT INTO CLIENTES VALUES(14,"Gloria","Fernandez",'23-35965852-5'," Constitución 323","GBA");
INSERT INTO CLIENTES VALUES(17,"Gonzalo","Lopez",'23-33587416-0',"Arias 2624"," GBA");
INSERT INTO CLIENTES VALUES(26,"Carlos","Garcia",'23-42321230-9',"Pasteur 322 - 2ºC","VIP");
INSERT INTO CLIENTES VALUES(50,"Micaela","Altieri",'23-22885566-5',"Santamarina 1255","GBA");

-- Hasta aca punto 1.3
-- Inicia el punto 2.1

DROP TABLE IF EXISTS CLIENTES_NEPTUNO;
CREATE TABLE CLIENTES_NEPTUNO(
IDCliente CHAR(5) PRIMARY KEY,
NombreCompania VARCHAR(50),
Direccion VARCHAR(50),
Ciudad VARCHAR(40),
Pais VARCHAR(25)
);
LOAD DATA INFILE 'C:/Users/alang/Documents/github/educacionit/intro_dbsql/Clientes_Neptuno.csv' INTO TABLE CLIENTES_NEPTUNO FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

ALTER TABLE CLIENTES_NEPTUNO MODIFY IDCliente VARCHAR(5), MODIFY NombreCompania VARCHAR(100) NOT NULL, MODIFY Pais VARCHAR(15) NOT NULL, RENAME TO CONTACTOS;

DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES(
COD_CLIENTE CHAR(4) PRIMARY KEY,
EMPRESA VARCHAR(50),
DIRECCION VARCHAR(50),
CIUDAD VARCHAR(40),
TELEFONO VARCHAR(25),
RESPONSABLE VARCHAR (25)
);

LOAD DATA INFILE 'C:/Users/alang/Documents/github/educacionit/intro_dbsql/Clientes.csv' INTO TABLE CLIENTES FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

ALTER TABLE CLIENTES MODIFY COD_CLIENTE VARCHAR(7), MODIFY EMPRESA VARCHAR(100) NOT NULL,MODIFY CIUDAD VARCHAR(25) NOT NULL, MODIFY TELEFONO INT UNSIGNED, MODIFY RESPONSABLE VARCHAR(30);

-- hice hasta el punto 5e, aqui arranca el punto 6

CREATE TABLE IF NOT EXISTS PEDIDOS(
NUMERO_PEDIDO INT,
CODIGO_CLIENTE VARCHAR(4),
FECHA_PEDIDO DATE,
FORMA_PAGO VARCHAR(8),
ENVIADO VARCHAR(2)
);

LOAD DATA INFILE 'C:/Users/alang/Documents/github/educacionit/intro_dbsql/Pedidos.csv' INTO TABLE PEDIDOS FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

ALTER TABLE PEDIDOS MODIFY NUMERO_PEDIDO INT PRIMARY KEY, MODIFY CODIGO_CLIENTE VARCHAR(7) NOT NULL, MODIFY FECHA_PEDIDO DATE NOT NULL, MODIFY FORMA_PAGO ENUM('CONTADO','APLAZADO','TARJETA'), MODIFY ENVIADO ENUM('SI','NO');

CREATE TABLE IF NOT EXISTS PRODUCTOS(
COD_PRODUCTO INT PRIMARY KEY,
SECCION VARCHAR(40),
NOMBRE VARCHAR(40),
IMPORTADO VARCHAR(8),
ORIGEN VARCHAR(25),
DIA INT,
MES INT,
ANO INT
);

LOAD DATA INFILE 'C:/Users/alang/Documents/github/educacionit/intro_dbsql/Productos.csv' INTO TABLE PEDIDOS FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' IGNORE 1 ROWS;
